[refactoring] mashup textfield 구현
mash-up-kr/mashup_Android pull request #270
Opened 2023-04-04 16:39 UTC by Ahn-seokjoo

## 작업 내역
- 매셥 텍스트 필드 구현했슴다
- compose ㄹㅇ 초보라서 피드백 많이 원함.

## 화면
|이전 화면|변경된 화면|
|---|---|
|input your previous image|input your current image|

close #<issue_number> 🦕

2023-04-07 17:18 UTC, jaeryo2357 requested changes
진짜 고생하셨어요 ㅜㅜㅜ 피드백 남겼습니다 :)

2023-04-07 17:18 UTC, jaeryo2357 commented on core/ui/src/main/java/com/mashup/core/ui/widget/MashUpTextField.kt
> +        }
엇 혹시 이 코드 추가된 이유가 처음 뷰 생성될 때 focus 주고 싶어서가 맞을까요??
그러면 이렇게 해야할 것 같아요!

```diff
- var focus by remember { mutableStateOf(focusBool) }
+ var focus by remember { mutableStateOf(false) } // 초기값은 무조건 false!


...

- if (text.isNotEmpty()) {   //focus랑 text.isNotEmpty랑 크게 관련이 없어보여서 지웠어요!
-            LaunchedEffect(key1 = Unit) {
-                focusRequester.requestFocus()
-                delay(100L)
-                keyboardController?.show()
-            }
-        }

+ LaunchedEffect(Unit) {
+           if (focusBool) { //초기 값이 true일때만 포커스 요청
+               focusRequester.requestFocus()
+                delay(100L)
+                keyboardController?.show()
+           }
+        }
```

+ 저는 delay(10L)으로 하면 오히려 키보드가 안올라오네요 100L을 해야만 올라오네요 ㅋㅋㅋ

2023-04-08 06:07 UTC, Ahn-seokjoo commented on core/ui/src/main/java/com/mashup/core/ui/widget/MashUpTextField.kt
> +                                ) else ColorFilter.tint(color = Green500)
[e58e1a1](https://github.com/mash-up-kr/mashup_Android/pull/270/commits/e58e1a1d677a115f2f2cc61d9acfcc2f17b6c2dc) ㅋㅎㅎ 넹

2023-04-08 06:10 UTC, Ahn-seokjoo commented on core/ui/src/main/java/com/mashup/core/ui/widget/MashUpTextField.kt
> +                shape = RoundedCornerShape(12.dp),
ca9ee04 반영했습니다

2023-04-08 07:08 UTC, Ahn-seokjoo commented on core/ui/src/main/java/com/mashup/core/ui/widget/MashUpTextField.kt
> +        }
맞는 것 같습니다 반영했습니다! 12a72da

2023-04-08 07:20 UTC, Ahn-seokjoo commented on core/ui/src/main/java/com/mashup/core/ui/widget/MashUpTextField.kt
> +            .border(
[46b4d2d](https://github.com/mash-up-kr/mashup_Android/pull/270/commits/46b4d2d6b86068c710bdc232d4f949259cd13f82) 반영했슴다

2023-04-08 12:51 UTC, jaeryo2357 approved these changes
확인했습니다!!

2023-05-14 13:37 UTC, Ahn-seokjoo commented
https://github.com/mash-up-kr/mashup_Android/assets/67602108/710e4ec5-d157-4407-9e97-1d8247bb51bd

영 상 첨 부

2023-05-15 12:23 UTC, Sookhee approved these changes
거의 한 달만에 머지..ㄷㄷ
수고하셨습니당. 👍

2023-05-15 12:27 UTC, jaeryo2357 approved these changes
:)

2023-05-15 12:27 UTC, merged