[Feature] 당근 흔들기 랭킹 API 세팅
mash-up-kr/mashup_Android pull request #272
Opened 2023-04-05 18:15 UTC by Ahn-seokjoo

## 작업 내역
- 랭킹 api 작업입니다
- swagger = https://api.dev-member.mash-up.kr/swagger-ui/index.html#/danggn-controller/getPlatformRankUsingGET

## 화면
- 화면 작업 없음

다음에 나갈 피쳐는 아니니 develop 머지 맞을까요~? 아님 당근으로 base 브랜치 하나 딸까요 다같이?
일단 develop으로 날렸지만 논의 후에 브랜치 변경하겠습니다~

close #<issue_number> 🦕

2023-04-07 17:28 UTC, jaeryo2357 requested changes
확인부탁드립니다! ㅜㅜ 수고하셨습니다

2023-04-07 17:28 UTC, jaeryo2357 commented on app/src/main/java/com/mashup/data/dto/DanggnAllMemberRankResponse.kt
> +    val `data`: List<Data>,
아..!! 이 부분 설명을 못드렸네요 ㅜㅜ
code, data, page 다 새로 정의할 필요없어요!!  
Retrofit API에서 사용해주신 Response의 제네릭 타입으로 넣어주게 되면 위 필드를 공통으로 파싱할 수 있어요!

```kotlin
data class MemberRankResponse(
       @Json(name = "memberId")
        val memberId: Int,
        @Json(name = "memberName")
        val memberName: String,
        @Json(name = "totalShakeScore")
        val totalShakeScore: Int
)
```

그래서 위처러만 정의하면 됩니다!

2023-04-07 17:28 UTC, jaeryo2357 commented on app/src/main/java/com/mashup/data/repository/DanggnRankRepository.kt
> +    ): Response<DanggnMemberRankResponse> {
```suggestion
    ): Response<List<MemeberRankResponse>> {
```

그래서 이렇게 정의하면 될 것 같네요!!

아래도 부탁드립니다 🤺

2023-04-07 17:28 UTC, jaeryo2357 commented on app/src/main/java/com/mashup/network/dao/DanggnRankDao.kt
> +    ): Response<DanggnAllMemberRankResponse>
```suggestion
    ): Response<List<MemeberRankResponse>>
```

여기도 이렇게 정의하면 될 것 같아요!! 나머지도 부탁드립니당

2023-04-07 17:28 UTC, jaeryo2357 commented on app/src/main/java/com/mashup/network/dao/DanggnRankDao.kt
> + * [swagger] https://api.dev-member.mash-up.kr/swagger-ui/index.html#/danggn-controller/getMemberRankUsingGET
스웨거 링크 적어두는 것도 좋네요!! 👍

2023-04-08 05:58 UTC, Ahn-seokjoo commented on app/src/main/java/com/mashup/network/dao/DanggnRankDao.kt
> + * [swagger] https://api.dev-member.mash-up.kr/swagger-ui/index.html#/danggn-controller/getMemberRankUsingGET
감사합니다?

2023-04-08 05:58 UTC, Ahn-seokjoo commented on app/src/main/java/com/mashup/network/dao/DanggnRankDao.kt
> +    ): Response<DanggnAllMemberRankResponse>
[33c611d](https://github.com/mash-up-kr/mashup_Android/pull/272/commits/33c611d303a4fb0d81e47d1cd8bf0b8d2957a73b)

2023-04-08 05:59 UTC, Ahn-seokjoo commented on app/src/main/java/com/mashup/data/repository/DanggnRankRepository.kt
> +    ): Response<DanggnMemberRankResponse> {
[33c611d](https://github.com/mash-up-kr/mashup_Android/pull/272/commits/33c611d303a4fb0d81e47d1cd8bf0b8d2957a73b) 수정 완료

2023-04-08 05:59 UTC, Ahn-seokjoo commented on app/src/main/java/com/mashup/data/dto/DanggnAllMemberRankResponse.kt
> +    val `data`: List<Data>,
[33c611d](https://github.com/mash-up-kr/mashup_Android/pull/272/commits/33c611d303a4fb0d81e47d1cd8bf0b8d2957a73b) 수정 완료

2023-04-08 06:45 UTC, jaeryo2357 approved these changes
확인했어용!

2023-04-08 06:46 UTC, merged