[feat] lazy column으로 변경 + 매시업 전체 인원 보여주기 (11명 이상)
mash-up-kr/mashup_Android pull request #412
Opened 2023-06-28 18:11 UTC by Ahn-seokjoo

## 작업 내역
- sample
추가한 인원만큼 보일 예정.
근데, 중요한 점이 있음....
lazy column으로 변경하니 scrollTo(0)가 안먹음 (item click이 안되는데, 해결방법 아시는분~)

- figma link
  :

## 화면
|이전 화면|변경된 화면|
|---|---|
|input your previous image|![image](https://github.com/mash-up-kr/mashup_Android/assets/67602108/29711101-cbba-4b29-b08e-aea3ebdfde87)|

close #<issue_number> 🦕

2023-06-28 18:12 UTC, Ahn-seokjoo commented
인원이제 서버에서 내려오는 만큼 보여줍니다

1. 근데, lazycolumn으로 변경하니 아이템 클릭이 안먹는데 알려주실분
2. 이전 기획이 기억이 안나는데 "당근을 더 흔들어서 랭킹 안에 들어보세요" 이건 이제 아예 쓸일이 없는지?

2023-06-29 14:22 UTC, jaeryo2357 requested changes
확인부탁드려요!

2023-06-29 14:22 UTC, jaeryo2357 commented on feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
> +        LazyColumn(
다시 Column으로 해도 될 것 같아요!! key Empty Ranking의 memberId를 UUID.random으로 만들어지는데 preview에서 이슈가 있었나봐요

2023-06-29 14:54 UTC, Ahn-seokjoo commented on feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
> +            // TODO 얘들아 나 이거 원래 기획이 기억이 안나 살려줘 그냥 없애도 되나?
5acc13e 수정 완료!!

2023-06-29 14:54 UTC, Ahn-seokjoo commented on feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingContent.kt
> +        LazyColumn(
0cdd9b4 수완!

2023-06-29 15:00 UTC, jaeryo2357 approved these changes
👍  ㅋㅋㅋㅋ 수고하셨어요 혹시 여유가 있다면 주석 중복된 부분이 조금 있어서 수정해주시면 감사하겠습니다 :0

2023-06-29 15:01 UTC, Ahn-seokjoo commented
이거 안스가 자꾸 억까함 ㅠ 빼고 머지할게요잉

2023-06-29 15:11 UTC, merged