[feat] 타이머 기능 구현
mash-up-kr/mashup_Android pull request #425
Opened 2023-07-01 17:09 UTC by Ahn-seokjoo

## 작업 내역
- sample
타이머 기능 넣었습니다
민욱이의 dateDiff 보고 진입시에 자동으로 타이머 시작하는 로직은 추가되어야 합니다.

- figma link
  : https://www.figma.com/file/kxgTs6r19oJz6ipQGYm83d/%EB%A7%A4%EC%89%AC%EC%97%85-%EC%95%B1?type=design&node-id=2-6&mode=design&t=YLjpU4LdetUrG0SI-0

## 화면
|이전 화면|변경된 화면|
|---|---|
|input your previous image|[영상.webm](https://github.com/mash-up-kr/mashup_Android/assets/67602108/b2824ec6-f749-407d-9bb8-6e1a45c6a690)
|

2023-07-01 17:16 UTC, Ahn-seokjoo commented on core/common/src/main/java/com/mashup/core/common/extensions/FlowExtention.kt
> +}
무한증식 플로우

2023-07-03 14:24 UTC, Ahn-seokjoo commented on core/common/src/main/java/com/mashup/core/common/utils/TimerUtils.kt
> +        job = CoroutineScope(EmptyCoroutineContext).launch(Dispatchers.IO) {
이러케 EmptyCoroutineContext로 만들어서 하는게 맞는지 모르겠어요
이전에 타이머 만들떈 그냥 viewModelScope로 만들었엇는데...
viewModelScope 내부를 보니 supervisorJob으로 coroutine context를 만드네요

2023-07-04 11:49 UTC, Sookhee commented on feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
> +    private val timer: MutableStateFlow<TimerUtils> = MutableStateFlow(TimerUtils())
이거 혹시 그냥 선언하면 동작 안하나요?
```kotlin
private val timer: TimerUtils = TimerUtils()

...
timer.startTimer()
```

2023-07-04 12:13 UTC, Sookhee commented on feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
> +    private fun getTimerData(value: Int) = mashUpScope {
지금 타이머 로직이 pull to refresh 했을 때만 돌아가도록 되어있는 것 같아여..
그래서 diffDate가 0일일 때 refresh를 안해주면 타이머가 안 돌아갈 것 같더라고요

updateAllRanking 밑에 이런 식으로 추가해주는거 어때여?
```kotlin
if (currentDateDiff.value <= 0) {
    getTimerData(currentRoundId.value)
}
```

2023-07-04 12:29 UTC, Sookhee commented on core/common/src/main/java/com/mashup/core/common/utils/TimerUtils.kt
> +        job = CoroutineScope(EmptyCoroutineContext).launch(Dispatchers.IO) {
음.. 밖에서 viewModelScope를 넘기는건 이상하려나?? 😅

2023-07-04 12:42 UTC, jaeryo2357 requested changes
확인했습니다~!

2023-07-06 13:05 UTC, Ahn-seokjoo commented on feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
> +    private val timer: MutableStateFlow<TimerUtils> = MutableStateFlow(TimerUtils())
ㅋㅋㅋㅋㅋㅋㅋㅋ안드개발하다보니 뭐든 stateflow를 해버리는 습관이;; 굿

2023-07-06 13:07 UTC, Ahn-seokjoo commented on core/common/src/main/java/com/mashup/core/common/utils/TimerUtils.kt
> +        job = CoroutineScope(EmptyCoroutineContext).launch(Dispatchers.IO) {
근데 안에서 job으로 가지고 있어야만 cancel 해줄 수 있지 않나용 ? job을 밖에서 받아오나용?

2023-07-06 13:16 UTC, Ahn-seokjoo commented on feature/danggn/src/main/java/com/mashup/feature/danggn/ranking/DanggnRankingViewModel.kt
> +    private val timer: MutableStateFlow<TimerUtils> = MutableStateFlow(TimerUtils())
[9580dcc](https://github.com/mash-up-kr/mashup_Android/pull/425/commits/9580dcc9ac1501ad9988ffc99c889529f65f7560) 넹

2023-07-06 13:19 UTC, jaeryo2357 approved these changes
👍  확인했습니다!! 짱짱

2023-07-08 15:54 UTC, Sookhee approved these changes
오 타이머 잘 돌아간다 👍👍
고생하셨어요

2023-07-08 15:54 UTC, Sookhee commented
근데 왜 깃모지 안써줘~ 8ㅅ8

2023-07-10 13:02 UTC, merged